"use client";

import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import { buttonVariants } from "@/components/ui/button";
import { generateQrPngDataUrl, generateQrSvg } from "@/lib/qr";
import { cn } from "@/lib/utils";

const CodeEditor = dynamic(
  () => import("@/components/CodeEditor").then((m) => m.CodeEditor),
  {
    ssr: false,
    loading: () => <div className="size-full animate-pulse bg-muted" />,
  },
);

export function QrGenerator() {
  const [text, setText] = useState("https://devforge.dev");
  const [svg, setSvg] = useState("");
  const [pngUrl, setPngUrl] = useState("");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    if (text.trim() === "") {
      setSvg("");
      setPngUrl("");
      setError(null);
      return;
    }

    Promise.all([generateQrSvg(text), generateQrPngDataUrl(text)])
      .then(([nextSvg, nextPng]) => {
        if (cancelled) return;
        setSvg(nextSvg);
        setPngUrl(nextPng);
        setError(null);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : "QR kod üretilemedi.");
      });

    return () => {
      cancelled = true;
    };
  }, [text]);

  const svgDataUrl = svg
    ? `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`
    : "";

  return (
    <div className="rounded-xl border border-border bg-card p-4">
      <h2 className="text-sm font-bold">QR Kod</h2>
      <div className="mt-3 grid grid-cols-1 gap-4 lg:grid-cols-[1.1fr_0.9fr]">
        <div className="h-24 overflow-hidden rounded-lg border border-border">
          <CodeEditor
            value={text}
            onChange={setText}
            language="plaintext"
            ariaLabel="QR kod girişi"
          />
        </div>

        <div className="flex flex-col items-center gap-3">
          <div className="flex size-[160px] items-center justify-center rounded-lg border border-border bg-white p-2">
            {error ? (
              <span className="text-center text-xs text-destructive">
                {error}
              </span>
            ) : svg ? (
              // Trusted markup generated by the `qrcode` package, not user HTML.
              <div
                className="size-full"
                dangerouslySetInnerHTML={{ __html: svg }}
              />
            ) : (
              <span className="text-xs text-muted-foreground">Metin girin</span>
            )}
          </div>

          <div className="flex w-full gap-2">
            <a
              href={pngUrl || undefined}
              download="devforge-qr.png"
              aria-disabled={!pngUrl}
              className={cn(
                buttonVariants({ variant: "outline", size: "sm" }),
                "flex-1",
                !pngUrl && "pointer-events-none opacity-50",
              )}
            >
              PNG İndir
            </a>
            <a
              href={svgDataUrl || undefined}
              download="devforge-qr.svg"
              aria-disabled={!svg}
              className={cn(
                buttonVariants({ variant: "outline", size: "sm" }),
                "flex-1",
                !svg && "pointer-events-none opacity-50",
              )}
            >
              SVG İndir
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
